resource_types:
  - name: ecs-task-definition
    type: docker-image
    source:
      repository: makotonakai/ecs-task-definition-resource

resources:
  - name: task-definition
    type: ecs-task-definition
    source:
      aws_access_key_id: ((aws_access_key_id))
      aws_secret_access_key: ((aws_secret_access_key))
      aws_region: ((aws_region))
      task_definition.json: ((task_definition.json))

jobs:
  - name: push-task-definition
    plan:
      - get: task-definition
      - put: task-definition
